name: update-with-todoist-stats
on: 
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'
  
jobs:
  update-readme:
    name: Update Todoist stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: README with Todoist
        uses: SiddharthShyniben/todoist-readme@0.0.1
        with: 
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: true

    
