name: README with Todoist
on: 
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'
  
jobs:
  update-readme:
    name: Update Todoist stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SiddharthShyniben/todoist-readme@v0.0.6
        with: 
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: true

    
